# Generated by Django 5.0.7 on 2024-08-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredialSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('prediales', models.TextField(blank=True, null=True)),
                ('link_cobro', models.TextField(blank=True, null=True)),
                ('primera_consulta', models.DateField(auto_now_add=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'prediales',
            },
        ),
    ]
