# Generated by Django 5.0.7 on 2024-08-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacienda', '0002_alter_predialsearch_primera_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predialsearch',
            name='primera_consulta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
