# Generated by Django 5.0.7 on 2024-08-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacienda', '0003_alter_predialsearch_primera_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='predialsearch',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
