# Generated by Django 5.0.7 on 2024-08-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacienda', '0004_predialsearch_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='predialsearch',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
