# Generated by Django 5.0.7 on 2024-08-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacienda', '0005_predialsearch_nombre_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredialUrlShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.TextField(blank=True, null=True)),
                ('short_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'prdiales-links-pagos',
            },
        ),
    ]
