# Generated by Django 5.0.7 on 2024-08-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacienda', '0006_predialurlshort'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios_keys',
            },
        ),
    ]
