# AVR -> alcaldia villa del rosario.
version: '3.9'
services:
  chatbotavr:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - media_volume:/app/media
    ports:
      - "8000:8000"
    container_name: apiChatbotAVR
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - IP_SERVER=${IP_SERVER}
      - CODIGO_EMPRESA=${CODIGO_EMPRESA}
      - USUARIO=${USUARIO}
      - PASSWD=${PASSWD}
      - TNSTOKEN=${TNSTOKEN}
    networks:
      - chatbotavr

networks:
  chatbotavr:
    driver: bridge
    external: true

volumes:
  media_volume:
